collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3219833
  brandStrength: 0
  lightness: 0.2909199
  brandColors:
    - '#D4E5F7'
    - '#6E90B3'
    - '#050D02'
    - '#B7A98F'
    - '#445533'
  rhythmicContrast: 0.3064516
typography_spectrum: 0.3986459
layout_spectrum: 0.4940263
name: NicolaKluge
